export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_EXITO = "OBTENER_EXITO";
export const OBTENER_ERROR = "OBTENER_ERROR";

export const GUARDAR_PRODUCTO = "GUARDAR_PRODUCTO";
export const GUARDAR_EXITO = "GUARDAR_EXITO";
export const GUARDAR_ERROR = "GUARDAR_ERROR";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_EXITO = "ELIMINAR_EXITO";
export const ELIMINAR_ERROR = "ELIMINAR_ERROR";

export const OBTENER_EDITAR = "OBTENER_EDITAR";
export const COMENZAR_EDITAR = "COMENZAR_EDITAR";
export const EDITAR_EXITO = "EDITAR_EXITO";
export const EDITAR_ERROR = "EDITAR_ERROR";