export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_EXITO = "OBTENER_EXITO";
export const OBTENER_ERROR = "OBTENER_ERROR";

export const GUARDAR_PRODUCTO = "GUARDAR_PRODUCTO";
export const GUARDAR_EXITO = "GUARDAR_EXITO";
export const GUARDAR_ERROR = "GUARDAR_ERROR";
